version: '3'

services:
  scheduler-backend:
    container_name: scheduler-backend
    build: ./backend
    command: gunicorn --access-logfile gunicorn.logs --bind :8000 scheduler_project.wsgi:application
    networks:
      - nginx-network
      - postgres-network
    env_file:
      - backend/.env.prod
    depends_on:
      - scheduler-db

  nginx:
    container_name: scheduler-nginx
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - scheduler-backend
    networks:
      - nginx-network
    expose:
      - "8000"

  scheduler-db:
    container_name: scheduler-db
    image: postgres:latest
    env_file:
      - backend/postgres.env
    networks:
      - postgres-network

networks:
  nginx-network:
    driver: bridge
  postgres-network:
    driver: bridge
