version: '3'

services:
  scheduler-backend:
    container_name: scheduler-backend
    build: ./backend
    command: gunicorn --access-logfile - --bind :8000 scheduler_project.wsgi:application
    volumes:
      - static_volume:/backend/static
    networks:
      - nginx-network
      - postgres-network
    environment:
      - ENV_FILE=.env.prod
    depends_on:
      - scheduler-db
    ports:
      - "8000:8000"
    restart: always

  scheduler-nginx:
    container_name: scheduler-nginx
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - scheduler-backend
    volumes:
      - static_volume:/backend/static
      - certs:/app/ssl:ro
    networks:
      - nginx-network
    restart: always

  scheduler-db:
    container_name: scheduler-db
    image: postgres:latest
    env_file:
      - backend/postgres.env
    networks:
      - postgres-network
    restart: always

networks:
  nginx-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  static_volume:
  certs:
