# Generated by Django 2.2.2 on 2019-07-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='building',
        ),
        migrations.AddField(
            model_name='classroom',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('time', models.TimeField()),
                ('classroomId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.Classroom')),
            ],
        ),
    ]
