# Generated by Django 2.2.2 on 2019-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190702_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('auditorium', models.IntegerField(blank=True)),
                ('professor', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('week_interval', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='classroomId',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
