# Generated by Django 2.2.2 on 2019-07-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190706_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='auditorium',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
