# Generated by Django 2.2.2 on 2019-07-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190706_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
