# Generated by Django 2.2.2 on 2019-07-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190706_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='auditorium',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
