# Generated by Django 2.2.2 on 2019-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20190706_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='auditorium',
            field=models.CharField(max_length=5),
        ),
    ]
