# Generated by Django 2.2.2 on 2019-07-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190707_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='ScheduleSubject',
        ),
    ]
