# Generated by Django 2.2.2 on 2019-07-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20190707_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulesubject',
            old_name='time_id',
            new_name='time',
        ),
    ]
