# Generated by Django 2.2.2 on 2019-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20190707_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletime',
            name='temp',
            field=models.TextField(default=''),
        ),
    ]
