# Generated by Django 2.2.2 on 2019-07-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_scheduletime_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletime',
            name='temp',
        ),
    ]
