# Generated by Django 2.2.2 on 2019-07-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_remove_scheduletime_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=10)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.Auditorium'),
        ),
    ]
