# Generated by Django 2.2.2 on 2019-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20190707_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('name_short', models.CharField(max_length=3)),
            ],
        ),
    ]
