# Generated by Django 2.2.2 on 2019-07-08 20:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_day'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='schedulesubject',
            managers=[
                ('subjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
