# Generated by Django 2.2.2 on 2019-07-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20190708_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletime',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
