# Generated by Django 2.2.5 on 2019-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20190708_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='building',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
