# Generated by Django 2.2.5 on 2019-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20190918_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesubject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='professor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
