# Generated by Django 2.2.5 on 2019-10-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20191002_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='building',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='professor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
