# Generated by Django 2.2.5 on 2019-10-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20191003_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='building',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='auditorium',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='schedulesubject',
            unique_together={('name', 'auditorium', 'day', 'time')},
        ),
    ]
