# Generated by Django 2.2.5 on 2019-10-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20191004_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesubject',
            name='group',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
