# Generated by Django 2.2.5 on 2019-10-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_schedulesubject_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesubject',
            unique_together={('name', 'auditorium', 'day', 'time', 'group')},
        ),
    ]
