# Generated by Django 2.2.5 on 2019-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_auto_20191004_1058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulesubject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='schedulesubject',
            constraint=models.UniqueConstraint(fields=('type', 'name', 'auditorium', 'day', 'time', 'group'), name='unique-subjects'),
        ),
    ]
