# Generated by Django 2.2.5 on 2019-10-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_auto_20191004_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='classroom',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
