# Generated by Django 2.2.5 on 2019-10-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_auditorium_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='classroom',
            field=models.IntegerField(),
        ),
    ]
