# Generated by Django 2.2.5 on 2019-10-07 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0025_auto_20191007_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupiedAuditorium',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('aud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Auditorium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
