# Generated by Django 2.2.5 on 2019-10-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_occupiedauditorium'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupiedauditorium',
            name='day_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.Day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulesubject',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.Day'),
        ),
    ]
