# Generated by Django 2.2.5 on 2019-10-07 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_auto_20191007_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupiedauditorium',
            name='time_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schedule.ScheduleTime'),
            preserve_default=False,
        ),
    ]
