# Generated by Django 2.2.5 on 2019-10-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0028_occupiedauditorium_time_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupiedauditorium',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
