# Generated by Django 2.2.5 on 2019-10-07 02:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0030_auto_20191007_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OccupiedAuditorium',
            new_name='ReservedAuditorium',
        ),
    ]
