# Generated by Django 2.2.5 on 2020-02-15 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('classroom', models.IntegerField()),
                ('building', models.CharField(max_length=15)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('name_short', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=150)),
                ('professor', models.CharField(blank=True, max_length=150, null=True)),
                ('group', models.CharField(max_length=50)),
                ('week_interval', models.IntegerField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler-app.Auditorium')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler-app.Day')),
                ('schedule_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler-app.ScheduleTime')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedAuditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler-app.Auditorium')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler-app.Day')),
                ('schedule_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler-app.ScheduleTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler-app.User')),
            ],
        ),
        migrations.AddConstraint(
            model_name='schedulesubject',
            constraint=models.UniqueConstraint(fields=('type', 'name', 'auditorium', 'day', 'schedule_time', 'group'), name='unique-schedule-subjects'),
        ),
        migrations.AddConstraint(
            model_name='reservedauditorium',
            constraint=models.UniqueConstraint(fields=('auditorium', 'day', 'schedule_time', 'reserve_date', 'user'), name='unique-reserved-auditoriums'),
        ),
    ]
